LINE_A_STOPS = [
    {"stop_id": "A01", "stop_name": "Balma-Gramont", "line": "A", "base_multiplier": 1.80},
    {"stop_id": "A02", "stop_name": "Argoulets", "line": "A", "base_multiplier": 1.20},
    {"stop_id": "A03", "stop_name": "Roseraie", "line": "A", "base_multiplier": 1.30},
    {"stop_id": "A04", "stop_name": "Jolimont", "line": "A", "base_multiplier": 1.40},
    {"stop_id": "A05", "stop_name": "Marengo-SNCF", "line": "A", "base_multiplier": 3.90},
    {"stop_id": "A06", "stop_name": "Jean Jaurès", "line": "A", "base_multiplier": 5.40},
    {"stop_id": "A07", "stop_name": "Capitole", "line": "A", "base_multiplier": 4.70},
    {"stop_id": "A08", "stop_name": "Esquirol", "line": "A", "base_multiplier": 4.10},
    {"stop_id": "A09", "stop_name": "Saint-Cyprien-République", "line": "A", "base_multiplier": 1.25},
    {"stop_id": "A10", "stop_name": "Patte-d'Oie", "line": "A", "base_multiplier": 1.50},
    {"stop_id": "A11", "stop_name": "Arènes", "line": "A", "base_multiplier": 2.05},
    {"stop_id": "A12", "stop_name": "Fontaine-Lestang", "line": "A", "base_multiplier": 1.10},
    {"stop_id": "A13", "stop_name": "Mermoz", "line": "A", "base_multiplier": 1.20},
    {"stop_id": "A14", "stop_name": "Bagatelle", "line": "A", "base_multiplier": 1.05},
    {"stop_id": "A15", "stop_name": "Mirail-Université", "line": "A", "base_multiplier": 1.60},
    {"stop_id": "A16", "stop_name": "Reynerie", "line": "A", "base_multiplier": 1.20},
    {"stop_id": "A17", "stop_name": "Bellefontaine", "line": "A", "base_multiplier": 1.30},
    {"stop_id": "A18", "stop_name": "Basso-Cambo", "line": "A", "base_multiplier": 1.70},
]
