LINE_B_STOPS = [
    {"stop_id": "B01", "stop_name": "Borderouge", "line": "B", "base_multiplier": 1.05},
    {"stop_id": "B02", "stop_name": "Trois Cocus", "line": "B", "base_multiplier": 0.70},
    {"stop_id": "B03", "stop_name": "La Vache", "line": "B", "base_multiplier": 0.75},
    {"stop_id": "B04", "stop_name": "Barrière de Paris", "line": "B", "base_multiplier": 0.80},
    {"stop_id": "B05", "stop_name": "Minimes-Claude Nougaro", "line": "B", "base_multiplier": 0.85},
    {"stop_id": "B06", "stop_name": "Canal du Midi", "line": "B", "base_multiplier": 0.80},
    {"stop_id": "B07", "stop_name": "Compans-Caffarelli", "line": "B", "base_multiplier": 0.90},
    {"stop_id": "B08", "stop_name": "Jeanne d'Arc", "line": "B", "base_multiplier": 0.95},
    {"stop_id": "B09", "stop_name": "Jean Jaurès", "line": "B", "base_multiplier": 1.50},
    {"stop_id": "B10", "stop_name": "François Verdier", "line": "B", "base_multiplier": 1.10},
    {"stop_id": "B11", "stop_name": "Carmes", "line": "B", "base_multiplier": 1.10},
    {"stop_id": "B12", "stop_name": "Palais de Justice", "line": "B", "base_multiplier": 1.05},
    {"stop_id": "B13", "stop_name": "Saint-Michel-Marcel Langer", "line": "B", "base_multiplier": 0.85},
    {"stop_id": "B14", "stop_name": "Empalot", "line": "B", "base_multiplier": 0.80},
    {"stop_id": "B15", "stop_name": "Saint-Agne SNCF", "line": "B", "base_multiplier": 1.00},
    {"stop_id": "B16", "stop_name": "Saouzelong", "line": "B", "base_multiplier": 0.75},
    {"stop_id": "B17", "stop_name": "Rangueil", "line": "B", "base_multiplier": 0.90},
    {"stop_id": "B18", "stop_name": "Faculté de Pharmacie", "line": "B", "base_multiplier": 0.85},
    {"stop_id": "B19", "stop_name": "Université Paul Sabatier", "line": "B", "base_multiplier": 0.95},
    {"stop_id": "B20", "stop_name": "Ramonville", "line": "B", "base_multiplier": 0.90},
]
